apiVersion: v1
kind: Pod
metadata:
  name: meu-pod-1
  labels:
    app: minha-aplicacao
spec:
  containers:
    - name: meu-container
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: meu-pod-2
  labels:
    app: minha-aplicacao
spec:
  containers:
    - name: meu-container
      image: nginx