apiVersion: v1
kind: ReplicationController
metadata:
  name: meu-rc
spec:
  replicas: 2
  selector:
    app: minha-aplicacao
  template:
    metadata:
      labels:
        app: minha-aplicacao
    spec:
      containers:
        - name: meu-container
          image: nginx