apiVersion: v1
clusters:
- cluster:
    certificate-authority: ca.crt
    server: https://<KUBERNETES_API_SERVER_ADDRESS>
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: username
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: username
  user:
    client-certificate: user.crt
    client-key: user.key