apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: username-csr
spec:
  groups:
  - system:authenticated
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
  request: <BASE64_ENCODED_CSR>