apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    function: front-end
  annotations:
    buildversion: v1.0
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: mypod-app
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0