- name: Create join token
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- debug: msg={{ join_command_raw.stdout }} 

- name: Set join_command as fact
  set_fact: join_command="{{ join_command_raw.stdout }}"