apiVersion: v1
kind: Pod
metadata:
  name: database
spec:
  containers:
    - name: database
      image: postgres:latest
      ports:
        - containerPort: 5432
      livenessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
      env:
      - name: POSTGRES_PASSWORD
        value: S3gr3d0