apiVersion: v1
kind: Pod
metadata:
  name: migration
spec:
  containers:
    - name: migration-init
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 20"]
      volumeMounts:
        - name: data-volume
          mountPath: /data
    - name: main-container
      image: nginx
      volumeMounts:
        - name: data-volume
          mountPath: /data
  initContainers:
    - name: init-migration
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 20"]
      volumeMounts:
        - name: data-volume
          mountPath: /data
  volumes:
    - name: data-volume
      emptyDir: {}