apiVersion: apps/v1
kind: <CHANGE-ME>
metadata:
  name: <CHANGE-ME>
spec:
  replicas: <CHANGE-ME>
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx
