apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  serviceAccountName: dashboard-sa
  volumes:
    - name: service-account-token
      projected:
        sources:
          - serviceAccountToken:
              path: my-token
              expirationSeconds: 7200
              audience: api
  containers:
    - name: my-app-container
      image: my-app-image
      volumeMounts:
        - name: service-account-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount