apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default:
      cpu: 500m
    defaultRequest:
      cpu: 500m
    max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: 100m
      memory: "25Mi"
    type: Container