apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    function: font-end
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "256m"
        cpu: 100m
      limits:
        memory: "512Mi"
        cpu: 1