apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
  - name: backend-container
    image: mysql
    env:
    - name: DB_HOST
      value: backend-db
  tolerations:
  - key: "example.com/my-taint"
    operator: "Equal"
    value: "backend-node"
    effect: "NoSchedule"