apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: frontend-container
    image: nginx
    ports:
    - containerPort: 80
  tolerations:
  - key: "example.com/my-taint"
    operator: "Exists"
    effect: "NoSchedule"