apiVersion: v1
kind: Namespace
metadata:
  name: homologacao
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: homologacao
  name: user-role
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "services"]
  verbs: ["create", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: homologacao
  name: user-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-role
subjects:
- kind: User
  name: <username>  # Substitua <username> pelo nome de usuário do usuário real