apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "services"]
  verbs: ["create", "list", "watch", "update"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-cluster-role
subjects:
- kind: User
  name: <username>  # Substitua <username> pelo nome de usuário do usuário real